#!/usr/bin/env bash

cd ../webapp-dist
git pull $1 master
git rm -r *
cd ../webapp
rm -rf dist
mkdir dist
npm run build
rsync -av ./dist/ ../webapp-dist
cd ../webapp-dist
if [[ `git status --porcelain` ]]; then
  git add -A .
  git commit -m "Deploy"
  git push $1 master
else
  echo "no changes"
fi;
