web: node ./bin/www
dev: supervisor ./bin/www

setup-deploy: rm -rf ../webapp-dist && cd ../ && git clone ssh://deployer@solar.dev.argh.team/home/deployer/repos/solar-front.git webapp-dist && cd webapp && chmod +x deploy
deploy: ./deploy ssh://deployer@solar.dev.argh.team/home/deployer/repos/solar-front.git
